### PR TITLE
syncing

### PR DESCRIPTION
**Pull request by FGDATA**

### CODE REVIEW

**Comment by onox** [comment]
I cannot merge PR's like these. The PR does not represent a valid "contribution"; there's no feature implemented or bug fixed. There is not even a description.

The reason that you had to do a merge is because I did some force pushing. Just reset to an early commit and then pull.

**Comment by FGDATA** [comment]
Ok.
I am a bit confused here, but it does not matter.

1. I do not do force pushes. Do you think this is a game? (pun intended, and not intended)
2. I like synced repositories, to be able to do fast forward. But I notice you really like to play the hard to get chicken. Including with the event on the c172p where you were pushing to show some strength of some sort (power play) and now, showing this is your project. 

In case of such hostility, I guess, I just do merges, instead of fast forward, that's all I can do.

Thanks a lot,
@IAHM-COL

**Comment by onox** [comment]
You're misunderstanding, I (not you) did a force push to my repository (onox/V-22). When you pulled in your FGEMEMBERS/V-22 branch, git noticed the branches were different (because I had force pushed to my repository), forcing git to do merge instead of fast forward.

This is the reason why people (in this case, me) should try to not do force pushes to master; it gives other people (like you) (who pull my repositories) problems. I knew this, but since this V-22 repository isn't as popular as the c172p-detailed for example, I hoped I could get away with it.

Anyway, I'm sorry for that, but in the end you should update your repository to reflect mine, since yours is a fork of mine. Merging your PR would be pointless for me and would make the history graph uglier than it can be.

I hope you understand.

**Comment by IAHM-COL** [comment]
ok
I am still wrapping my brain around.

You suggest, I

1) git reset hard to a previous commit
2) git pull your remote , and thus get synced

Because you git push forced?! (meaning, you are the one who made such
mistake!)

Your suggestion will definitely make the repos synced, but, It will
potentially conflict severely with submodules, specially in clones that are
still pointing to commits that will dissapear.

I am almost sure I can't do that safely without compromising or risking
compromising several users and potential users of FGDATA next. Having
merged commits, because you refuse to accept a pull request will make my
fork look uglier, granted, but the whole infrastructure will be safe.


@IAHM-COL

**Comment by onox** [comment]
> will make my fork look uglier, granted, but the whole infrastructure will be safe.

In that case you should keep your repository as it currently is.

**Comment by FGDATA** [comment]
Yes. that's also what I think. I was just hoping that with this pull
request, the repos will come synced, and the future pulls would come
fast-forwarded. Not as merge commits.
Since I have commits you no longer have because you git forced, then the
only way I know of syncing is that you get the PR.

Best,
IH-COL

**Comment by onox** [comment]
Can you check on Github how often people pull/clone the FGMEMBERS/V-22 repository?

**Comment by FGDATA** [comment]
I am afraid github only track naive clones and pull. It does not seem to
track when it is pulled as submodules. I know several of the people that
uses the submodules, as they have told me in PMs, they do clone the whole
package! Meaning they also have the V-22

**Pull request closed without merging**
